### ISSUE TITLE
Can't start btholt/complete-intro-to-sql containerdocker 

### ISSUE THREAD

**Issue by agentx3** [btholt/complete-intro-to-sql#10]
When I try to run
 `docker run -e POSTGRES_PASSWORD=lol --name=sql -p 5432:5432 -d --rm btholt/complete-intro-to-sql`
 I get
`WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
e69219312f972c308fc979ae1227dd5562b77e5cc4045e96b923a381c02cfd09`
and nothing happens.

I looked around for solutions and one that seemed to do anything was adding a `--platform linux/arm64/v8` option, which shuts up the warning message, but either way both `docker ps -a` and `docker container ls -a` do not display the btholt/complete-intro-to-sql container. I am running Ubuntu.

**Comment by patlo-git** [comment]
@agentx3 Where did you get that command?

**Comment by agentx3** [comment]
> @agentx3 Where did you get that command?

`docker run -e POSTGRES_PASSWORD=lol --name=sql -p 5432:5432 -d --rm btholt/complete-intro-to-sql` was directly copied and pasted from the video titled `JSON vs JSONB` from around 30 seconds in.

**Comment by RoystonS** [comment]
I've already raised this with FEM directly: the docker image has only been published for M1 Macs.

You can rebuild the image yourself using Brian's Dockerfile here: https://github.com/btholt/complete-intro-to-sql-container, but hopefully they'll publish an image for standard x86 soon.

**Comment by agentx3** [comment]
Thanks for sharing that repo, I got it working.

For anyone that might need to go the same route, here's brief instructions on what I did
1. Clone the container repo
2. Enter the same directory as the Dockerfile and run `docker build -t <whatever you want the image name to be> . `
2b. If docker can't resolve github's host name you can try `docker build --network host -t <w/e image name> . `
3. Then run the original `docker run` command (the first one in the OP) but replace `btholt/complete-intro-to-sql` with whatever your named your image
