### ISSUE TITLE
recipeguru database not appearing in btholt/complete-intro-to-sql docker image even after pulling latest

### ISSUE THREAD

**Issue by ashoofly** [btholt/complete-intro-to-sql#12]
Hello, I also checked my image sha against the one you showed [here](https://frontendmasters.com/courses/sql/json-vs-jsonb/), and it matches, but I do not see the recipeguru database still. I do get the amd64 warning, but I don't think that would be a factor.

```
$ docker pull btholt/complete-intro-to-sql:latest
latest: Pulling from btholt/complete-intro-to-sql
Digest: sha256:86f9d1e155bf35b82abe2a14b56e0141644d1660d391e6d97cc58a8db6f30950
Status: Image is up to date for btholt/complete-intro-to-sql:latest
docker.io/btholt/complete-intro-to-sql:latest

$ docker run -e POSTGRES_PASSWORD=lol --name=sql -p:5432:5432 -d --rm btholt/complete-intro-to-sql
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
a49337a8b95055511edc290c395c88c5345724a9242902461f0b909c59ef5ab6

$ docker exec -u postgres -it sql psql
psql (14.4 (Debian 14.4-1.pgdg110+1))
Type "help" for help.

postgres=# \l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 omdb      | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(4 rows)
```
I think I can just run your [recipes.sql](https://sql.holt.courses/recipes.sql) file as a workaround, but I am filing a bug here in case this is an issue for other people..

**Comment by abdallahrabiaa** [comment]
I have also this issue

**Comment by abdallahrabiaa** [comment]
try this 
``sudo docker container run -e POSTGRES_PASSWORD=lol --name=sql btholt/complete-intro-to-sql

**Comment by ayubmja2** [comment]
I am running into the same issue here as well. I'm running parrotOS the moment I tried running the command I got this warning "WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v2) and no specific platform was requested" -- which doesn't allow the container to run at all.

**Comment by 0xNunana** [comment]
Currently facing the same issue 
 $docker pull btholt/complete-intro-to-sql:latest
latest: Pulling from btholt/complete-intro-to-sql
Digest: sha256:86f9d1e155bf35b82abe2a14b56e0141644d1660d391e6d97cc58a8db6f30950
Status: Image is up to date for btholt/complete-intro-to-sql:latest
docker.io/btholt/complete-intro-to-sql:latest
   $ docker run -e POSTGRES_PASSWORD=lol --name=sql -d -p 5433:5432 --rm btholt/complete-intro-to-sql
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
8458966fff38daf44c344467238dc5ed2dade42a279acc87158fd82282738495

$ docker exec -u postgres -it sql psql
Error response from daemon: No such container: sql

**Comment by pdjsh** [comment]
I have the same issue, I ran the container without the -d flag so I could see the logs and this is what shows up

`exec /usr/local/bin/docker-entrypoint.sh: exec format error`

Seems like the issue is that the image was built on macOS, and there is some issue running it on Linux or maybe other operating systems. I myself am using Arch Linux, in case that helps

@btholt maybe you could take a look at this?

**Comment by ayubmja2** [comment]
> I have the same issue, I ran the container without the -d flag so I could see the logs and this is what shows up
> 
> 
> 
> `exec /usr/local/bin/docker-entrypoint.sh: exec format error`
> 
> 
> 
> Seems like the issue is that the image was built on macOS, and there is some issue running it on Linux or maybe other operating systems. I myself am using Arch Linux, in case that helps
> 
> 
> 
> @btholt maybe you could take a look at this?

- That is the issue I ran across this issue 2 months ago. @btholt or front end masters has to rebuild the docker image so it can support all architectures. He built it on the new Mac M1-2 chip. I was using parrot os when I ran across this issue.

I got existing thinking it got fixed when I started getting notifications from here.

**Comment by ayubmja2** [comment]
> Currently facing the same issue 
> 
>  $docker pull btholt/complete-intro-to-sql:latest
> 
> latest: Pulling from btholt/complete-intro-to-sql
> 
> Digest: sha256:86f9d1e155bf35b82abe2a14b56e0141644d1660d391e6d97cc58a8db6f30950
> 
> Status: Image is up to date for btholt/complete-intro-to-sql:latest
> 
> docker.io/btholt/complete-intro-to-sql:latest
> 
>    $ docker run -e POSTGRES_PASSWORD=lol --name=sql -d -p 5433:5432 --rm btholt/complete-intro-to-sql
> 
> WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
> 
> 8458966fff38daf44c344467238dc5ed2dade42a279acc87158fd82282738495
> 
> 
> 
> $ docker exec -u postgres -it sql psql
> 
> Error response from daemon: No such container: sql
> 
> 
> 
> 

If you do not own a Mac Os with an m1 chip you will not be able to go forward. In this part I just watched the videos and skipped that part.

**Comment by pdjsh** [comment]
I got to the part where I need the omdb set up, so since the docker image doesn't work I had to find a workaround for this. What I ended up doing is, I found this github repo https://github.com/btholt/complete-intro-to-sql-container/tree/main, and it has a Dockerfile there. You can clone the repo and build the image yourself. It also has a link to what it's using as data, which is https://github.com/credativ/omdb-postgresql/tree/master
So you can also see what the Dockerfile is doing and apply the same changes to the database on your own, which is what I ended up doing. It's a bit of a hassle, but it's better than nothing, until the docker image issue is fixed

**Comment by ayubmja2** [comment]
I'll check it out once I have time. Thank you.
