### ISSUE TITLE
Failing saving PSQL session data after turning off computer

### ISSUE THREAD

**Issue by Biki-das** [btholt/complete-intro-to-sql#2]
while running docker and psql session , every things runs perfect but after closing pc all the data in the PC is losed,? what am i doing wrong any directions from here?

**Comment by btholt** [comment]
It'll be a Docker issue that it's not running right after the PC resumes. You're best bet [is to start with Docker site](https://docs.docker.com/search/?q=desktop%20sleep) and see if other people are having the same issue.

**Comment by Biki-das** [comment]
thanks @btholt for the answer!
