### ISSUE TITLE
[Bug] Update and Delete insert typo missing type

### ISSUE THREAD

**Issue by K3ARN3Y** [btholt/complete-intro-to-sql#4]
In [Updates and Deletes](https://sql.holt.courses/lessons/data/updates-and-deletes), you have the following code

```sql
INSERT INTO ingredients
  (title, image)
VALUES
  ('not real 1', 'delete.jpg'),
  ('not real 2', 'delete.jpg');
```
This will cause an error: "ERROR:  null value in column "type" of relation "ingredients" violates not-null constraint"

In the previous lesson [Tables](https://sql.holt.courses/lessons/databases-and-tables/tables), we altered the table to have `type` be `NOT NULL`.

```sql
ALTER TABLE ingredients
ADD COLUMN image VARCHAR ( 255 ),
ADD COLUMN type VARCHAR ( 50 ) NOT NULL;
```

I suggest to change it to:

```sql
INSERT INTO ingredients
  (title, image, type)
VALUES
  ('not real 1', 'delete.jpg', 'fake'),
  ('not real 2', 'delete.jpg', 'fake');
```

**Comment by dtauer** [comment]
@K3ARN3Y Thank you for reporting all these issues! I will update the course website and redeploy.

Regarding this issue, Brian recreated the table in the course and added a default for the column:

```sql
ADD COLUMN type VARCHAR ( 50 ) NOT NULL DEFAULT 'vegetable';
```

I updated the Tables code in the notes and added a call out for using default.
