### ISSUE TITLE
[Bug] Need to re-insert recipes_photos data

### ISSUE THREAD

**Issue by K3ARN3Y** [btholt/complete-intro-to-sql#7]
In [Joins and Constraints Project](https://sql.holt.courses/lessons/joins-and-constraints/project), it assumes you have data in `recipes_photos` when we don't anymore.

We need to seed the data in:
```sql
INSERT INTO recipes_photos
  (recipe_id, url)
VALUES
  (1, 'cookies1.jpg'),
  (1, 'cookies2.jpg'),
  (1, 'cookies3.jpg'),
  (1, 'cookies4.jpg'),
  (1, 'cookies5.jpg'),
  (2, 'empanada1.jpg'),
  (2, 'empanada2.jpg'),
  (3, 'jollof1.jpg'),
  (4, 'shakshuka1.jpg'),
  (4, 'shakshuka2.jpg'),
  (4, 'shakshuka3.jpg'),
  (5, 'khachapuri1.jpg'),
  (5, 'khachapuri2.jpg');
-- no pictures of xiao long bao
```

Optionally, you can add this data in on the [Foreign Keys](https://sql.holt.courses/lessons/joins-and-constraints/foreign-keys) page when we drop and re-create the tables.

**Comment by dtauer** [comment]
There's a link on this page to recipes.sql which will reseed the DB.

**Comment by K3ARN3Y** [comment]
@dtauer, technically yes. But if you watch the lecture, it even trips up Brian.
This appears before that link.
```sql
SELECT DISTINCT ON (r.recipe_id)
  *
FROM
  recipes r
LEFT JOIN
  recipes_photos rp
ON
  r.recipe_id = rp.recipe_id;
```

It would best for the student to not get tripped up on something like this.
Options:
1. suggestions above
2. Move the paragraph with the link above the query.

**Comment by dtauer** [comment]
Ah, yes, I see what you are saying. If people try the hint before reseeding the DB, it will fail. Thanks for the clarification.
