### ISSUE TITLE
[Bug] Missing videos?

### ISSUE THREAD

**Issue by K3ARN3Y** [btholt/complete-intro-to-sql#8]
Hi,

I am watching the [course replay](https://frontendmasters.com/workshops/complete-intro-sql/). I think there is a missing video(s).

Day 2 - Part 5 ends abruptly while talking about pgAmin.
Day 2 - Part 6 picks up at GIN.

Missing under Query Performance:

[Explain](https://sql.holt.courses/lessons/query-performance/explain)
[Indexes](https://sql.holt.courses/lessons/query-performance/indexes)
[Create an Index](https://sql.holt.courses/lessons/query-performance/create-an-index)

Also, Day 2 Parts 8 and 9 should be swapped. Currently, Part 8 is the conclusion.

**Comment by dtauer** [comment]
Yes, we had some technical issues and reshot portions of the course later (which is why you may see course replays out of order or with abrupt cuts). The final course has all these items addressed. It should be release very soon!
